const PATHCONSTANTS = {
    HOME: '/',
    QUOTES: {
        INDEX: '/quotes',
        AUTO: '/quotes/auto',
        HOME: '/quotes/home',
        MEXICO: '/quotes/mexico',
        MOTORCYCLE: '/quotes/motorcycle',
        RENTERS: '/quotes/renter',
        SURETY: '/quotes/surety-bond',
        SR22: '/quotes/sr22',
        LIABILITY: '/quotes/liability',
    },
    PRODUCTS: {
        INDEX: '/products',
        AUTO: '/products/auto',
        HOME: '/products/home',
        MEXICO: '/products/mexico',
        MOTORCYCLE: '/products/motorcycle',
        RENTERS: '/products/renter',
        SURETY: '/products/surety-bond',
        SR22: '/products/sr22',
    },
    LOCATIONS: {
        INDEX: '/locations',
        AUSTIN: '/locations/austin',
        HOUSTON: '/locations/houston',
        SAN_ANTONIO: '/locations/san-antonio',
        DALLAS: '/locations/dallas',
        CORPUS_CHRISTI: '/locations/corpus-christi',
        VICTORIA: '/locations/victoria',
    },
    ABOUT: {
        INDEX: '/about',
        CONTACT: '/about/contact',
        CAREERS: '/about/careers',
        REVIEWS: '/about/reviews',
    },
    PAYMENTS: '/payments',
};
export default PATHCONSTANTS